<?php

/** * *********************************************************
 * Copyright 2013 (C) Xeno Innovations, Inc.
 * ALL RIGHTS RESERVED
 * @Author:       Damian Suess
 * Document:      xpmtPage
 * Created Date:  Apr 23, 2013
 * Status:        {unstable/pre-alpha/alpha/beta/stable}
 * Description:
 *
 *
 * Change Log:
 *
 */
namespace xenoPMT\Core
{
  class xpmtPage
  {
    /* Private vars */

    /**
     * Extra header information to add.
     * Must use the function AddHeaderTag() to add to this
     * @var string
     */
    private $_extHeader;

    /* Public Vars */

    /**
     * Page title to display in HTML <title></title> tag
     * @var string
     */
    public $Title = "";

    /*
     * Header                       - Extra Header information added by Modules/Core
     * Body                         - Body data generated by Module
     * Footer                       - Custom Fooder data (set by Theme init file)
     * Block["custom"]              - Custom Block Data
     * Hook["themeFunctionName"]    - Custom function generated in Theme-Init ?or? Theme-POST-ModuleLoad
     *
     */




    function __construct()
    {
      /* TODO:
       * [ ] Set default site title
       *    [ ] Use language settings for title
       * [ ] Set default page properties
       */
    }

    function __destruct() { }


    /**
     * Sets page title such as "$subTitle - [xenoPMT]"
     * @param string $subTitle    Page title
     */
    public function SetPageTitle($subTitle)
    {
      /* TODO:
       *  [ ] Pull title from system settings
       */
      $this->Title = $subTitle . " - [xenoPMT]";
    }

    /**
     * Outputs HTML format of extra header information to add besides what the current
     * theme is suggesting
     *
     * @return string Extended Header Information
     */
    public function GetHeader()
    {
      return $this->_extHeader;
    }

    /**
     *
     * @param string $nodeName      Name of the HTML node
     * @param array $arrProperties  Properties of html node
     * @param string $data          Data to display
     */
    public function AddHeaderTag($nodeName, $arrProperties, $data)
    {
      /*
       * 1.  <title>TestData</title>
       * 2.  <metatag propName1=Val1 />
       */
    }

  }
}
?>
